name: pytest

on: [ push, pull_request ]

jobs:
  pytest:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade uv
          uv pip install --system -r requirements.txt
          uv pip install --system -r requirements-dev.txt

      - name: Run tests
        run: |
          pytest tagstudio/tests/
